# Sudoku Solver


## Setup
Create example gridset. Printable using numpy array  
test prints

In [ ]:
import numpy as np

global grid
grid =   np.matrix([[5,3,0,0,7,0,0,0,0],
                    [6,0,0,1,9,5,0,0,0],
                    [0,9,8,0,0,0,0,6,0],
                    [8,0,0,0,6,0,0,0,3],
                    [4,0,0,8,0,3,0,0,1],
                    [7,0,0,0,2,0,0,0,6],
                    [0,6,0,0,0,0,2,8,0],
                    [0,0,0,4,1,9,0,0,5],
                    [0,0,0,0,8,0,0,7,9]])

print(grid)

print()
print(grid[:,3])


In [2]:
import numpy as np

global grid

grid =   np.matrix([[1,0,0,2,0,0,0,0,7],
                    [0,0,0,0,0,0,6,9,0],
                    [7,0,0,3,0,0,8,0,0],
                    [5,6,0,9,0,8,0,0,0],
                    [0,2,0,7,0,0,0,0,1],
                    [0,0,0,0,0,0,0,0,0],
                    [0,0,4,0,7,0,0,0,5],
                    [2,5,0,8,0,0,9,0,0],
                    [0,0,0,0,4,0,0,0,0]])

## Function valid(x,y,n) 
returns true if n is valid in position x,y - else false


In [3]:
def valid_show_working(x,y, n):
    global grid

    #test prints:
    print("current value at x,y is ", grid[x,y])
    row = grid[x,:]
    print(row)
    col = grid[:,y]
    print(col)
    print()

    # check vertical and horizontal
    if (n in row): return False #vertical
    if (n in col): return False #horizontal

    # check local square
    xO = (x // 3) * 3
    yO = (y // 3) * 3
    print("local square origin: ",xO,yO)
    print("local square: ")    
    block = grid[xO:xO+3,yO:yO+3]
    print(block)
    if (n in block): return False

    return True

print(valid_show_working(2,1,7))    

current value at x,y is  0
[[7 0 0 3 0 0 8 0 0]]
[[0]
 [0]
 [0]
 [6]
 [2]
 [0]
 [0]
 [5]
 [0]]

False


In [4]:
def valid(x,y, n):
    global grid

    # check vertical and horizontal
    row = grid[x,:]
    col = grid[:,y]
    if (n in row): return False #vertical
    if (n in col): return False #horizontal

    # check local square
    xO = (x // 3) * 3
    yO = (y // 3) * 3
    block = grid[xO:xO+3,yO:yO+3]
    if (n in block): return False

    return True

print(valid(2,1,7))    

False


## solve()
Recursively brute force the grid to solve   

In [6]:
def solve():
    global grid
    for x in range(9):
        for y in range(9):
            if grid[x,y] == 0:
                for n in range(1,10):
                    if valid(x,y,n):
                        grid[x,y] = n
                        solve()
                        grid[x,y] = 0
                return
    print(grid)

solve()


[[1 9 6 2 8 4 3 5 7]
 [8 3 2 1 5 7 6 9 4]
 [7 4 5 3 9 6 8 1 2]
 [5 6 1 9 2 8 4 7 3]
 [4 2 9 7 6 3 5 8 1]
 [3 7 8 4 1 5 2 6 9]
 [9 8 4 6 7 2 1 3 5]
 [2 5 7 8 3 1 9 4 6]
 [6 1 3 5 4 9 7 2 8]]
