# Sudoku Solver


## Setup
Create example gridset. Printable using numpy array  
test prints

In [9]:
import numpy as np

global grid
grid =   np.matrix([[5,3,0,0,7,0,0,0,0],
                    [6,0,0,1,9,5,0,0,0],
                    [0,9,8,0,0,0,0,6,0],
                    [8,0,0,0,6,0,0,0,3],
                    [4,0,0,8,0,3,0,0,1],
                    [7,0,0,0,2,0,0,0,6],
                    [0,6,0,0,0,0,2,8,0],
                    [0,0,0,4,1,9,0,0,5],
                    [0,0,0,0,8,0,0,7,9]])

print(grid)

print()
print(grid[:,3])


[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]

[[0]
 [1]
 [0]
 [0]
 [8]
 [0]
 [0]
 [4]
 [0]]


## Function valid(x,y,n) 
returns true if n is valid in position x,y - else false


In [2]:
def valid_show_working(x,y, n):
    global grid

    #test prints:
    print("current value at x,y is ", grid[x,y])
    row = grid[x,:]
    print(row)
    col = grid[:,y]
    print(col)
    print()

    # check vertical and horizontal
    if (n in row): return False #vertical
    if (n in col): return False #horizontal

    # check local square
    xO = (x // 3) * 3
    yO = (y // 3) * 3
    print("local square origin: ",xO,yO)
    print("local square: ")    
    block = grid[xO:xO+3,yO:yO+3]
    print(block)
    if (n in block): return False

    return True

print(valid_show_working(2,1,7))    

current value at x,y is  9
[[0 9 8 0 0 0 0 6 0]]
[[3]
 [0]
 [9]
 [0]
 [0]
 [0]
 [6]
 [0]
 [0]]

local square origin:  0 0
local square: 
[[5 3 0]
 [6 0 0]
 [0 9 8]]
True


In [10]:
def valid(x,y, n):
    global grid

    # check vertical and horizontal
    row = grid[x,:]
    col = grid[:,y]
    if (n in row): return False #vertical
    if (n in col): return False #horizontal

    # check local square
    xO = (x // 3) * 3
    yO = (y // 3) * 3
    block = grid[xO:xO+3,yO:yO+3]
    if (n in block): return False

    return True

print(valid(2,1,7))    

True


## solve()
Recursively brute force the grid to solve   

In [11]:
def solve():
    global grid
    for x in range(9):
        for y in range(9):
            if grid[x,y] == 0:
                for n in range(1,10):
                    if valid(x,y,n):
                        grid[x,y] = n
                        solve()
                        grid[x,y] = 0
                return
    print(grid)

solve()


[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
